#! /bin/bash

grep '^Building ' `lastBuiltTrunkHealthLog` | fgrep 'completed successfully' > /dev/null
if [ "$?" -eq "0" ] ; then
    echo "Build completed successfully"
    exit 0
else
    grep '^building ' `lastBuiltTrunkHealthLog` | fgrep ' failed' > /dev/null
    if [ "$?" -eq "0" ] ; then
	echo "Build failed"
	exit 1
    else
	echo "Build is still working"
	exit 2
    fi
fi
exit
    
